# https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image  
# https://docs.docker.com/get-started/08_using_compose/
version: '3.9'

services:
    mongo:
        image: mongo
        container_name: mevn-mongodb
        volumes:
            - mongodata:/data/db
            - mongodata:/data/configdb
        ports:
            - 22222:27017
    ubuntu:
        container_name: mevn-node
        build:
            dockerfile: Dockerfile-node        
        command: ["sleep","infinity"]
        volumes:
            - ./node:/home/node
        depends_on:
            - mongo
        ports:
            - 3333:3000
            - 5555:5173
    mongo-express:
        image: mongo-express
        container_name: mevn-mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        depends_on:
            - mongo
        ports:
            - 9999:8081
volumes:
    mongodata:
networks:
    default:
        name: mevn-nodenet