services:
    mongo:
        image: mongo
        container_name: hypernode_mongodb
        environment: 
            MONGO_INITDB_ROOT_USERNAME: 
            MONGO_INITDB_ROOT_PASSWORD: 
        volumes:
            - hypernode_mongodata:/data/db
            - hypernode_mongodata:/data/configdb
        ports:
            - 22222:27017   # mongodb
    ubuntu:
        container_name: hypernode
        build:
            dockerfile: Dockerfile-node        
        command: ["sleep","infinity"]
        volumes:
            - ./node:/home/node
        depends_on:
            - mongo
        ports:
            - 3333:3000     # express
            - 5555:5173     # vite dev
    mongo-express:
        image: mongo-express
        container_name: hypernode-mongo-express
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: 
            ME_CONFIG_BASICAUTH_PASSWORD: 
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: 
            ME_CONFIG_MONGODB_ADMINPASSWORD: 
        #    - ME_CONFIG_MONGODB_ENABLE_ADMIN=root
        #    - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        depends_on:
            - mongo
        ports:
            - 9999:8081     # mongo-express
volumes:
    hypernode_mongodata:
networks:
    default:
        name: hypernode-nodenet