FROM ubuntu:jammy

LABEL maintainer="rimbert.rudisch-sommer@fh-hagenberg.at"

COPY src /src

# Install scripts
RUN cd /src \
    && chmod 755 *.sh \
    && /src/install-apt.sh \
    && /src/basic_tools.sh \
    && curl -o setupnode20.sh -fsSL https://deb.nodesource.com/setup_20.x \
    && /bin/sh /src/setupnode20.sh \
    && apt-get install -y nodejs \
    && npm install nodemon --global \
    && npm install express-generator --global \
    && npm install typescript -g \
    && npm install ts-node -g
